app_name: officer-filing-api    
group: api    
weight: 900
routes:
  1: ^/officer-filing
  2: ^/transactions/.*/officers
  3: ^/private/transactions/.*/officers
  4: ^/transactions/.*/officers/.*
  5: ^/officer-filing/company/.*/stop-screen-checks/.*
