# Spring Actuator
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.endpoints.access.default=read_only
management.endpoints.web.exposure.include=health
management.endpoints.web.path-mapping.health=${MANAGEMENT_ENDPOINTS_WEB_PATH_MAPPING_HEALTH}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

nationality.list=${NATIONALITY_LIST}

# Spring MongoDB
spring.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

# Spring JSON
spring.jackson.property-naming-strategy=SNAKE_CASE

# LOGGING
logging.level.uk.gov.companieshouse.officerfiling.api=${LOGGING_LEVEL}
logging.level.org.springframework.web=${WEB_LOGGING_LEVEL:INFO}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=${REQUEST_LOGGING_LEVEL:INFO}
